version: "3"
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "db_shop"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"

  demo-shop:
    depends_on:
      - mysqldb
    image: sergfedorov/demo-shop
    container_name: backend
    restart: always
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db_shop
