name: Setup
description: 'Checkout source and Java setup'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'