name: Java setup
description: 'Java setup'
runs:
  using: "composite"
  steps:
    - name: Java setup
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'