name: Build and Deploy

on:
  push:
    branches: master

jobs:

  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Java setup
        uses: ./.github/actions/java-setup
      - name: Unit test code coverage
        run: mvn jacoco:check@jacoco-check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Java setup
        uses: ./.github/actions/java-setup
      - name: Execute unit tests
        run: mvn '-Dtest=com.demo.shop.tests.unit.*Test' test
      - name: Execute integration tests
        run: mvn '-Dtest=com.demo.shop.tests.integration.*Tests' test
      - name: Execute consumer contract tests
        run: mvn '-Dtest=com.demo.shop.tests.contract.consumer.*Test' test
      - name: Execute provider contract tests
        run: mvn '-Dtest=com.demo.shop.tests.contract.provider.*Test' test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Java setup
        uses: ./.github/actions/java-setup

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t sergfedorov/demo-shop .
      - name: Publish image to docker hub
        run: docker push sergfedorov/demo-shop:latest

      - name: Check if docker-compose.yaml updated
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            docker-compose:
              - 'docker-compose.yaml'
      - name: Copy docker-compose.yaml to server
        if: steps.changes.outputs.docker-compose == 'true'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 3.64.193.172
          username: ${{ secrets.EC2_SSH_USER }}
          password: ${{ secrets.EC2_SSH_PASSWORD }}
          port: 22
          source: docker-compose.yaml
          target: /home/ubuntu

  deploy:
    needs: build
    runs-on: ec-2
    steps:
      - name: Pull image from docker hub and restart docker
        run: sudo docker compose pull && sudo docker compose up -d

  e2e_test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Java setup
        uses: ./.github/actions/java-setup
      - name: Execute E2E tests
        run: mvn '-Dtest=com.demo.shop.tests.e2e.*Tests' test -P remote